name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test scalingo-18
      run: make test-scalingo-18
    - name: Test scalingo-20
      run: make test-scalingo-20
